//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigView
    {
        public int ID { get; set; }
        public string Название_Команды { get; set; }
        public string Никнейм { get; set; }
        public Nullable<int> Возраст { get; set; }
        public string Страна { get; set; }
        public string Турнир { get; set; }
        public string Жанр { get; set; }
        public string Игра { get; set; }
    }
}
