//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class KomandiTurniri
    {
        public int ID_KomandiTurniri { get; set; }
        public int Team_ID { get; set; }
        public int Igroki_ID { get; set; }
        public int Turniri_ID { get; set; }
    
        public virtual Igrokis Igrokis { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Turniris Turniris { get; set; }
    }
}
