//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bazadannihPPEntities : DbContext
    {
        public bazadannihPPEntities()
            : base("name=bazadannihPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Igrokis> Igrokis { get; set; }
        public virtual DbSet<KomandiTurniri> KomandiTurniri { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Turniris> Turniris { get; set; }
        public virtual DbSet<PlayersView> PlayersView { get; set; }
        public virtual DbSet<TeamsView> TeamsView { get; set; }
        public virtual DbSet<TournamentsView> TournamentsView { get; set; }
        public virtual DbSet<BigView> BigView { get; set; }
    }
}
