//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersView
    {
        public int ID_Игрока { get; set; }
        public string Имя_Игрока { get; set; }
        public Nullable<int> Возраст { get; set; }
        public string Страна { get; set; }
    }
}
